In [5]:
# 601

numbers = [int(input()) for _ in range(12)]

for i in range(0, len(numbers), 3):
    print("".join(f"{num:3}" for num in numbers[i:i+3]))

even_index_sum = sum(numbers[i] for i in range(0, len(numbers), 2))
print(even_index_sum)

56
45
43
22
3
1
39
20
93
18
44
83
 56 45 43
 22  3  1
 39 20 93
 18 44 83
278

In [7]:
# 602

cards = [input() for _ in range(5)]
values = {'J': 11, 'Q': 12, 'K': 13, 'A': 1}
total = sum(values[card] if card in values else int(card) for card in cards)
print(total)

5
10
K
3
A
32

In [8]:
# 603

numbers = [int(input()) for _ in range(10)]
top_3 = sorted(numbers, reverse=True)[:3]
print(" ".join(map(str, top_3)))

40
32
12
29
20
19
38
48
57
44
57 48 44

In [9]:
# 604

from collections import Counter
numbers = [int(input()) for _ in range(10)]
count = Counter(numbers)
mode, frequency = count.most_common(1)[0]
print(f"{mode} {frequency}")

34
18
22
32
18
29
30
38
42
18
18 3

In [10]:
# 605

scores = [int(input()) for _ in range(10)]
scores.remove(max(scores))
scores.remove(min(scores))
print(sum(scores))
print(f"{sum(scores)/len(scores):.2f}")

89
78
67
80
75
98
77
89
76
60
631
78.88

In [16]:
# 606

rows, cols = int(input()), int(input())
matrix = [[col - row for col in range(cols)] for row in range(rows)]
for row in matrix:
    print(" ".join(f"{num:4}" for num in row))

5
10
   0    1    2    3    4    5    6    7    8    9
  -1    0    1    2    3    4    5    6    7    8
  -2   -1    0    1    2    3    4    5    6    7
  -3   -2   -1    0    1    2    3    4    5    6
  -4   -3   -2   -1    0    1    2    3    4    5

In [17]:
# 607

scores_list = []

for student_id in range(1, 4):
    print(f"The {student_id}st student:")
    scores = [int(input()) for _ in range(5)]
    scores_list.append(scores)

for student_id, scores in enumerate(scores_list, start=1):
    total = sum(scores)
    average = total / len(scores)
    print(f"Student {student_id}")
    print(f"#Sum {total}")
    print(f"#Average {average:.2f}")

The 1st student:
78
89
88
70
60
The 2st student:
90
78
66
68
78
The 3st student:
69
97
70
89
90
Student 1
#Sum 385
#Average 77.00
Student 2
#Sum 380
#Average 76.00
Student 3
#Sum 415
#Average 83.00

In [18]:
# 608

matrix = [[int(input()) for _ in range(3)] for _ in range(3)]

max_value = max(max(row) for row in matrix)
min_value = min(min(row) for row in matrix)

max_index = [(i, j) for i, row in enumerate(matrix) for j, val in enumerate(row) if val == max_value][0]
min_index = [(i, j) for i, row in enumerate(matrix) for j, val in enumerate(row) if val == min_value][0]

print(f"Index of the largest number {max_value} is: {max_index}")
print(f"Index of the smallest number {min_value} is: {min_index}")

6
4
8
39
12
3
-3
49
33
Index of the largest number 49 is: (2, 1)
Index of the smallest number -3 is: (2, 0)

In [20]:
# 609

print("Enter matrix 1:")
matrix1 = [[int(input(f"[{i+1}, {j+1}]: ")) for j in range(2)] for i in range(2)]

print("Enter matrix 2:")
matrix2 = [[int(input(f"[{i+1}, {j+1}]: ")) for j in range(2)] for i in range(2)]

print("Matrix 1:")
for row in matrix1:
    print(" ".join(map(str, row)))

print("Matrix 2:")
for row in matrix2:
    print(" ".join(map(str, row)))

sum_matrix = [[matrix1[i][j] + matrix2[i][j] for j in range(2)] for i in range(2)]

print("Sum of 2 matrices:")
for row in sum_matrix:
    print(" ".join(map(str, row)))

Enter matrix 1:
[1, 1]: 3
[1, 2]: 5
[2, 1]: 7
[2, 2]: 5
Enter matrix 2:
[1, 1]: 6
[1, 2]: 9
[2, 1]: 8
[2, 2]: 3
Matrix 1:
3 5
7 5
Matrix 2:
6 9
8 3
Sum of 2 matrices:
9 14
15 8

In [21]:
# 610

temperatures = []

for week in range(1, 5):
    print(f"Week {week}:")
    weekly_temperatures = []
    for day in range(1, 4):
        temp = float(input(f"Day {day}: "))
        weekly_temperatures.append(temp)
    temperatures.extend(weekly_temperatures)

average_temp = sum(temperatures) / len(temperatures)
highest_temp = max(temperatures)
lowest_temp = min(temperatures)

print(f"Average: {average_temp:.2f}")
print(f"Highest: {highest_temp:.1f}")
print(f"Lowest: {lowest_temp:.1f}")

Week 1:
Day 1: 23.1
Day 2: 24
Day 3: 23.5
Week 2:
Day 1: 32
Day 2: 33
Day 3: 35.3
Week 3:
Day 1: 29
Day 2: 30
Day 3: 26
Week 4:
Day 1: 27.6
Day 2: 25
Day 3: 28.8
Average: 28.11
Highest: 35.3
Lowest: 23.1